name: Rust on MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        # os: [macos-latest]
        os: [ubuntu-latest, windows-lates, macos-latest]
        # version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    # runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    
    
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
          name: TC-ID-Generator
          path: ./target/release/TC-Id-Generator-${{ matrix.os }}
      
